const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');
const {resumirRendimientoSegmentado,bandaCalibracion,rangoMuestra}=require('../services/pickTracking');
const {inyectarNonce,transformarHtml}=require('../middleware/entornoBanner');
const {crearHashesEstilosInline}=require('../services/csp');
const {evaluarAlertas}=require('../services/operationalAlerts');const {puertosPool,calendarioNecesitaRevision}=require('../services/dataQuality');
const {registrarEstadoCron,leerEstadoCron}=require('../services/cronStatus');
function pick(extra={}){return{estado:'acertado',estimacion:72,confianza:'alta',muestra:14,fecha_partido:new Date('2026-08-01'),liga:{id:39,nombre:'Premier',temporada:2026},mercado:{id:'goles_over_25',base_id:'goles_over_25',nombre:'Más de 2.5',alcance:'total',periodo:0},...extra};}
test('segmenta picks y construye calibración con sólo resueltos',()=>{const a=resumirRendimientoSegmentado([pick(),pick({estado:'fallado',estimacion:68}),pick({estado:'pendiente',estimacion:90})]);assert.equal(a.segmentos.liga[0].total,3);assert.equal(a.segmentos.periodo[0].etiqueta,'Partido completo');assert.equal(a.calibracion.find(x=>x.id==='60-69').efectividad,0);assert.equal(bandaCalibracion(100),'90-100');assert.equal(rangoMuestra(14),'10-19');});
test('inyecta nonce sólo en bloques inline y conserva scripts externos',()=>{const html='<html><head><style>.a{}</style></head><body><script>ok()</script><script src="/x.js"></script></body></html>';const salida=inyectarNonce(html,'abc');assert.match(salida,/<style nonce="abc">/);assert.match(salida,/<script nonce="abc">/);assert.match(salida,/<script src="\/x.js">/);assert.match(transformarHtml(html,{staging:true,nonce:'abc'}),/ENTORNO DE PRUEBA/);});
test('CSP no conserva unsafe-inline y genera hashes para estilos heredados',()=>{assert.doesNotMatch(fs.readFileSync('server.js','utf8'),/unsafe-inline/);assert.ok(crearHashesEstilosInline('public').every(x=>/^'sha256-/.test(x)));});
test('alertas cubren cron, cuota, partidos, redis, pool y pagos',()=>{const alertas=evaluarAlertas({cron:{ultima_ejecucion_exitosa:null},cuota:{restantes:3},problemas:{partidos_ns_atrasados:8},redis:'no_disponible',version:{diferencias:true,instancias:[]},pagos:{webhook_pago_fallos:1,discrepancias_suscripcion:2}},{solicitudes:100,respuestas_429:25,por_estado:{'5xx':10}},{},new Date());const codigos=new Set(alertas.map(a=>a.codigo));for(const codigo of ['CRON_ATRASADO','CUOTA_BAJA','PARTIDOS_ATRASADOS','REDIS_CAIDO','VERSION_POOL','WEBHOOK_PAGO_FALLANDO','SUSCRIPCION_INCONSISTENTE','HTTP_5XX_ALTO','HTTP_429_ALTO'])assert.ok(codigos.has(codigo));});
test('configura ambos puertos del pool sin convertir el índice en timeout',()=>{assert.deepEqual(puertosPool({APP_POOL_PORTS:'3000 3001'}),[3000,3001]);assert.deepEqual(puertosPool({APP_ENVIRONMENT:'staging'}),[3100,3101]);assert.doesNotMatch(fs.readFileSync('services/dataQuality.js','utf8'),/.map(consultarVersionPuerto)/);});
test('sólo marca calendarios próximos con una antigüedad proporcional',()=>{const ahora=new Date('2026-08-24T12:00:00Z');const liga=(proximo,actualizado)=>({proximo_partido:new Date(proximo),ultima_actualizacion:new Date(actualizado)});assert.equal(calendarioNecesitaRevision(liga('2026-08-26T12:00:00Z','2026-08-23T11:59:00Z'),ahora),true);assert.equal(calendarioNecesitaRevision(liga('2026-09-03T12:00:00Z','2026-08-18T12:00:00Z'),ahora),false);assert.equal(calendarioNecesitaRevision(liga('2026-09-20T12:00:00Z','2026-08-09T11:59:00Z'),ahora),true);assert.equal(calendarioNecesitaRevision(liga('2026-10-16T12:00:00Z','2026-07-01T00:00:00Z'),ahora),false);});
test('estado del cron conserva el último éxito tras un fallo',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cron-status-'));const env={CRON_STATUS_FILE:path.join(dir,'estado.json')};registrarEstadoCron('ejecutando','hourly',env,new Date('2026-08-01T00:00:00Z'));registrarEstadoCron('exitoso','hourly',env,new Date('2026-08-01T00:05:00Z'));registrarEstadoCron('fallido','hourly',env,new Date('2026-08-01T01:00:00Z'));const estado=leerEstadoCron(env);assert.equal(estado.estado,'fallido');assert.equal(estado.ultima_ejecucion_exitosa,'2026-08-01T00:05:00.000Z');});
