const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');
const {resumirRendimientoSegmentado,bandaCalibracion,rangoMuestra}=require('../services/pickTracking');
const {inyectarNonce,transformarHtml}=require('../middleware/entornoBanner');
const {crearHashesEstilosInline}=require('../services/csp');
const {evaluarAlertas}=require('../services/operationalAlerts');const {puertosPool,filtroPartidosPasadosSinResultado,resumirCobertura}=require('../services/dataQuality');
const {registrarEstadoCron,leerEstadoCron}=require('../services/cronStatus');
const {revalidarLote}=require('../services/fixtureRevalidation');
function pick(extra={}){return{estado:'acertado',estimacion:72,confianza:'alta',muestra:14,fecha_partido:new Date('2026-08-01'),liga:{id:39,nombre:'Premier',temporada:2026},mercado:{id:'goles_over_25',base_id:'goles_over_25',nombre:'Más de 2.5',alcance:'total',periodo:0},...extra};}
test('segmenta picks y construye calibración con sólo resueltos',()=>{const a=resumirRendimientoSegmentado([pick(),pick({estado:'fallado',estimacion:68}),pick({estado:'pendiente',estimacion:90})]);assert.equal(a.segmentos.liga[0].total,3);assert.equal(a.segmentos.periodo[0].etiqueta,'Partido completo');assert.equal(a.calibracion.find(x=>x.id==='60-69').efectividad,0);assert.equal(bandaCalibracion(100),'90-100');assert.equal(rangoMuestra(14),'10-19');});
test('inyecta nonce sólo en bloques inline y conserva scripts externos',()=>{const html='<html><head><style>.a{}</style></head><body><script>ok()</script><script src="/x.js"></script></body></html>';const salida=inyectarNonce(html,'abc');assert.match(salida,/<style nonce="abc">/);assert.match(salida,/<script nonce="abc">/);assert.match(salida,/<script src="\/x.js">/);assert.match(transformarHtml(html,{staging:true,nonce:'abc'}),/ENTORNO DE PRUEBA/);});
test('CSP no conserva unsafe-inline y genera hashes para estilos heredados',()=>{assert.doesNotMatch(fs.readFileSync('server.js','utf8'),/unsafe-inline/);assert.ok(crearHashesEstilosInline('public').every(x=>/^'sha256-/.test(x)));});
test('alertas cubren cron, cuota, partidos, redis, pool y pagos',()=>{const alertas=evaluarAlertas({cron:{ultima_ejecucion_exitosa:null},cuota:{restantes:3},problemas:{partidos_ns_atrasados:8},redis:'no_disponible',version:{diferencias:true,instancias:[]},pagos:{webhook_pago_fallos:1,discrepancias_suscripcion:2}},{solicitudes:100,respuestas_429:25,por_estado:{'5xx':10}},{},new Date());const codigos=new Set(alertas.map(a=>a.codigo));for(const codigo of ['CRON_ATRASADO','CUOTA_BAJA','PARTIDOS_ATRASADOS','REDIS_CAIDO','VERSION_POOL','WEBHOOK_PAGO_FALLANDO','SUSCRIPCION_INCONSISTENTE','HTTP_5XX_ALTO','HTTP_429_ALTO'])assert.ok(codigos.has(codigo));});
test('configura ambos puertos del pool sin convertir el índice en timeout',()=>{assert.deepEqual(puertosPool({APP_POOL_PORTS:'3000 3001'}),[3000,3001]);assert.deepEqual(puertosPool({APP_ENVIRONMENT:'staging'}),[3100,3101]);assert.doesNotMatch(fs.readFileSync('services/dataQuality.js','utf8'),/.map(consultarVersionPuerto)/);});
test('calidad toma la fecha de consulta y sólo busca partidos pasados sin resultado',()=>{const ahora=new Date('2026-08-24T12:00:00Z');const filtro=filtroPartidosPasadosSinResultado(ahora);assert.equal(filtro.fecha.$lt.toISOString(),'2026-08-24T10:00:00.000Z');assert.equal(filtro.fecha.$gte.toISOString(),'2026-07-25T12:00:00.000Z');assert.ok(filtro.$or[0].estado.$in.includes('NS'));assert.ok(!filtro.$or[0].estado.$in.includes('FT'));assert.deepEqual(filtro.$or[1].$and[0].estado.$in,['FT','AET','PEN']);});
test('separa estadísticas sin consultar, en reintento y sin cobertura',()=>{assert.deepEqual(resumirCobertura({total:10,completos:6,no_disponibles:2,por_consultar:1}),{total:10,completos:6,pendientes:2,por_consultar:1,en_reintento:1,no_disponibles:2,porcentaje_total:60,porcentaje_obtenible:75});});
test('la revalidación masiva queda limitada a diez partidos',async()=>{let limite;const consulta={select(){return this},sort(){return this},limit(valor){limite=valor;return this},async lean(){return Array.from({length:10},(_,i)=>({api_id:i+1}));}};const vistos=[];const resultado=await revalidarLote({estado:'NS'},{limite:99,modelo:{find(){return consulta}},revalidar:async id=>{vistos.push(id);return{recibido:true}}});assert.equal(limite,10);assert.equal(resultado.consultados,10);assert.deepEqual(vistos,[1,2,3,4,5,6,7,8,9,10]);});
test('estado del cron conserva el último éxito tras un fallo',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cron-status-'));const env={CRON_STATUS_FILE:path.join(dir,'estado.json')};registrarEstadoCron('ejecutando','hourly',env,new Date('2026-08-01T00:00:00Z'));registrarEstadoCron('exitoso','hourly',env,new Date('2026-08-01T00:05:00Z'));registrarEstadoCron('fallido','hourly',env,new Date('2026-08-01T01:00:00Z'));const estado=leerEstadoCron(env);assert.equal(estado.estado,'fallido');assert.equal(estado.ultima_ejecucion_exitosa,'2026-08-01T00:05:00.000Z');});
